package com.sheldondesousa.uncork.model

import com.sheldondesousa.uncork.ui.guided.WineRegions
import java.text.Normalizer

/** Which half of the Chat tab is driving the conversation right now. */
internal enum class ChatMode { Undecided, Curious, FindWine }

/** The deterministic, Kotlin-driven question sequence for the "find a wine" path. */
internal enum class FindWineStep { Type, Country, Taste }

internal sealed interface ModeChoice {
    data object Curious : ModeChoice
    data object FindWine : ModeChoice
}

/** Fixed, hardcoded copy for the deterministic flow — never generated by Gemma. */
internal object ChatFlowText {
    const val MODE_CHOICE =
        "Hi, I'm UnCork — think of me as your personal sommelier. Are you **curious about " +
            "wines and pairings**, or would you like me to **find a wine** for you?"
    const val CURIOUS_LABEL = "Curious about wines and pairings"
    const val FIND_WINE_LABEL = "Find a wine"
    const val Q1_TYPE =
        "What are you in the mood for: **red**, **rosé**, **white**, **sparkling**, " +
            "**sweet**, or **fortified**?"
    const val Q2_COUNTRY = "Any **country** or **province** you prefer?"
    const val Q3_TASTE =
        "Any preference for taste?\n\n" +
            "##Body (weight)##\n**Light, Medium, Full**\n\n" +
            "##Tannin (dryness)##\n**Smooth, Moderate, Astringent**\n\n" +
            "##Acidity (sourness)##\n**Soft, Crisp, Tart**\n\n" +
            "##Sweetness (sugar)##\n**Bone-Dry, Off-Dry, Sweet**"
    const val CURIOUS_TRANSITION = "Happy to chat — what's on your mind about wine or pairings?"

    fun questionFor(step: FindWineStep): String = when (step) {
        FindWineStep.Type -> Q1_TYPE
        FindWineStep.Country -> Q2_COUNTRY
        FindWineStep.Taste -> Q3_TASTE
    }

    fun apology(question: String): String = "I'm sorry I couldn't quite catch that. $question"
}

internal fun String.chatNormalized(): String =
    Normalizer.normalize(lowercase(), Normalizer.Form.NFD)
        .replace(Regex("\\p{M}+"), "")
        .replace(Regex("[^a-z0-9 ]"), " ")
        .replace(Regex("\\s+"), " ")
        .trim()

private fun String.containsPhrase(phrase: String): Boolean {
    val candidate = phrase.chatNormalized()
    return candidate.isNotBlank() &&
        Regex("(^| )${Regex.escape(candidate)}( |\$)").containsMatchIn(this)
}

private val NO_PREFERENCE_PHRASES = listOf(
    "no preference", "no preferences", "not sure", "dont know", "do not know",
    "skip", "any", "anything", "whatever", "surprise me", "doesnt matter",
    "does not matter", "no idea", "not fussed", "not picky", "idk",
)

internal fun isNoPreference(reply: String): Boolean {
    val normalized = reply.chatNormalized()
    return NO_PREFERENCE_PHRASES.any { normalized == it || normalized.startsWith("$it ") }
}

/**
 * Distinguishes a real tangent or wine question (worth a brief Gemma detour before handing
 * control back to the deterministic Q1-Q3 flow) from noise or an ambiguous short word (e.g.
 * "res") that should just get an apology and a repeat of the current question.
 */
internal fun isLikelyDigression(reply: String): Boolean {
    if (reply.contains('?')) return true
    val wordCount = reply.chatNormalized().split(' ').count(String::isNotBlank)
    return wordCount >= 4
}

private val FIND_WINE_KEYWORDS = listOf(
    "find a wine", "find wine", "find me a wine", "search for a wine", "search",
    "recommend", "recommendation", "suggest", "looking for a wine", "help me find",
)
private val CURIOUS_KEYWORDS = listOf(
    "curious", "chat", "talk about wine", "pairing", "pairings", "learn about wine",
    "question about wine", "general",
)

internal fun matchModeChoice(reply: String): ModeChoice? {
    val normalized = reply.chatNormalized()
    if (normalized == "1") return ModeChoice.Curious
    if (normalized == "2") return ModeChoice.FindWine
    val matchesFind = FIND_WINE_KEYWORDS.any(normalized::contains)
    val matchesCurious = CURIOUS_KEYWORDS.any(normalized::contains)
    return when {
        matchesFind && !matchesCurious -> ModeChoice.FindWine
        matchesCurious && !matchesFind -> ModeChoice.Curious
        else -> null
    }
}

// Deliberately narrower than FIND_WINE_KEYWORDS: mid-conversation, "recommend"/"suggest" alone
// (e.g. "what would you recommend with steak?") should stay a normal chat answer, not yank the
// user into the structured flow. Only an explicit ask to find/search for a wine switches modes.
private val FIND_WINE_SWITCH_PHRASES = listOf(
    "find a wine", "find me a wine", "find wine for me", "search for a wine",
    "help me find a wine", "let's find a wine", "lets find a wine",
    "start the wine finder", "switch to find a wine", "can we find a wine",
    "i want to find a wine", "id like to find a wine",
)

internal fun requestsFindWineSwitch(reply: String): Boolean {
    val normalized = reply.chatNormalized()
    return FIND_WINE_SWITCH_PHRASES.any(normalized::contains)
}

private val TYPE_KEYWORDS: Map<String, List<String>> = linkedMapOf(
    "red" to listOf("red"),
    "rose" to listOf("rose", "rosé", "pink"),
    "white" to listOf("white"),
    "sparkling" to listOf("sparkling", "bubbly", "champagne", "prosecco", "cava"),
    "sweet" to listOf("sweet", "dessert wine", "dessert"),
    "fortified" to listOf("fortified", "port", "sherry", "madeira"),
)

internal fun matchWineType(reply: String): String? {
    val normalized = reply.chatNormalized()
    val matches = TYPE_KEYWORDS.filterValues { keywords ->
        keywords.any { keyword -> normalized.containsPhrase(keyword) }
    }.keys
    return matches.singleOrNull()
}

internal data class LocationMatch(val country: String, val province: String)

private val COUNTRY_ALIASES = linkedMapOf(
    "french" to "France", "italian" to "Italy", "spanish" to "Spain",
    "portuguese" to "Portugal", "argentine" to "Argentina", "argentinian" to "Argentina",
    "chilean" to "Chile", "australian" to "Australia", "usa" to "United States",
    "america" to "United States", "american" to "United States",
    "german" to "Germany", "austrian" to "Austria", "greek" to "Greece",
    "kiwi" to "New Zealand",
)

internal fun matchLocation(reply: String): LocationMatch? {
    val normalized = reply.chatNormalized()
    for ((country, provinces) in WineRegions.catalog) {
        for (province in provinces) {
            if (normalized.containsPhrase(province)) {
                return LocationMatch(country = country, province = province)
            }
        }
    }
    for (country in WineRegions.catalog.keys) {
        if (normalized.containsPhrase(country)) {
            return LocationMatch(country = country, province = WinePreferences.UNKNOWN)
        }
    }
    val alias = COUNTRY_ALIASES.entries.firstOrNull { (phrase, _) -> normalized.containsPhrase(phrase) }
    return alias?.let { LocationMatch(country = it.value, province = WinePreferences.UNKNOWN) }
}

internal data class TasteMatch(
    val body: String? = null,
    val tannin: String? = null,
    val acidity: String? = null,
    val sweetness: String? = null,
) {
    val isEmpty: Boolean get() = body == null && tannin == null && acidity == null && sweetness == null
}

// Vocabulary sourced from Docs/Body.md, Docs/Tannin.md, Docs/Acidity.md, Docs/Sweetness.md —
// the sommelier synonym lists curated for each of the three tiers per characteristic. Internal
// (not private) so KaggleConversationResponder can reuse them as phrase evidence when checking
// whether a web result's free text supports a recorded body/tannin/acidity preference, since a
// web-synthesized card's structured field isn't as reliably populated as Kaggle's precomputed
// column.
internal val BODY_KEYWORDS = linkedMapOf(
    "Light-Bodied" to listOf(
        "light-bodied", "light bodied", "light", "delicate", "crisp", "lean", "ethereal",
        "zesty", "racy", "bright", "quaffable", "airy", "chiseled",
    ),
    "Medium-Bodied" to listOf(
        "medium-bodied", "medium bodied", "medium", "balanced", "versatile", "supple",
        "round", "fleshy", "approachable", "juicy", "smooth", "moderate", "fluid",
    ),
    "Full-Bodied" to listOf(
        "full-bodied", "full bodied", "full", "bold", "rich", "opulent", "robust",
        "powerful", "muscular", "viscous", "mouth-filling", "mouth filling", "dense",
        "velvety", "chewy", "fat",
    ),
)
internal val TANNIN_KEYWORDS = linkedMapOf(
    "Smooth" to listOf(
        "smooth", "soft tannin", "low tannin", "mellow tannin", "silky", "velvety",
        "supple", "resolved", "melted", "polished", "seamless", "satin", "integrated",
        "cashmere",
    ),
    "Moderate" to listOf(
        "moderate tannin", "medium tannin", "moderate", "structured", "chalky",
        "fine-grained", "fine grained", "firm", "grippy", "dusty", "chewy", "fleshy",
        "textured", "savory",
    ),
    "Astringent" to listOf(
        "astringent", "high tannin", "aggressive", "drying", "harsh", "auster",
        "austere", "green", "angular", "coarse", "gripping", "youthful", "puckering",
    ),
)
internal val ACIDITY_KEYWORDS = linkedMapOf(
    "Soft" to listOf(
        "soft acid", "soft", "low acid", "mellow acid", "flabby", "flat", "plush",
        "languid", "round", "smooth", "fleshy", "broad", "coating", "baked", "jammy",
        "mellow", "overripe", "low-toned", "low toned",
    ),
    "Crisp" to listOf(
        "crisp", "bright acid", "fresh acid", "medium acid", "lively", "bright",
        "balanced", "fresh", "animated", "defined", "clean", "tailored", "snappy",
        "juicy", "mouth-watering", "mouth watering", "tangy", "fruity-tart",
        "fruity tart", "zesty",
    ),
    "Tart" to listOf(
        "tart", "high acid", "electric", "racy", "vibrant", "zippy", "laser-focused",
        "laser focused", "sharp", "chiseled", "linear", "angular", "cutting", "citric",
        "searing", "bracing", "pucker-inducing", "pucker inducing", "zingy",
    ),
)
private val SWEETNESS_KEYWORDS = linkedMapOf(
    "Bone-Dry" to listOf(
        "bone-dry", "bone dry", "dry", "austere", "savory", "chiseled",
    ),
    "Off-Dry" to listOf(
        "off-dry", "off dry", "semi-sweet", "semi sweet", "lush", "succulent", "mellow",
    ),
    "Sweet" to listOf(
        "sweet", "dessert", "luscious", "lucious", "honeyed", "nectarous", "syrupy",
    ),
)

internal fun matchTaste(reply: String): TasteMatch {
    val normalized = reply.chatNormalized()
    fun <T> firstMatch(keywordMap: Map<T, List<String>>): T? =
        keywordMap.entries.firstOrNull { (_, keywords) ->
            keywords.any(normalized::containsPhrase)
        }?.key
    return TasteMatch(
        body = firstMatch(BODY_KEYWORDS),
        tannin = firstMatch(TANNIN_KEYWORDS),
        acidity = firstMatch(ACIDITY_KEYWORDS),
        sweetness = firstMatch(SWEETNESS_KEYWORDS),
    )
}
